#!/usr/bin/python3

import argparse
import json
from azure import Azure

parser = argparse.ArgumentParser(prog="acr-setup-rbac", description="")
parser.add_argument("-rg", "--resource-group", required=True,
                    type=str, help="Resource group name.")
parser.add_argument("-r", "--registry", required=True,
                    type=str, help="Container registry name.")

args = parser.parse_args()

az_group_id = Azure.get_group_id(args.resource_group)
az_rdac = Azure.create_sp_rbac(az_group_id, "Contributor")
print(json.dumps(az_rdac))
az_rdac_clientid = az_rdac["clientId"]

az_registry_id = Azure.get_acr_id(args.registry)

Azure.create_role(az_rdac_clientid, az_registry_id, "AcrPush")
