#!/usr/bin/python3

import argparse
from buildtools.lib.docker import add_image_tag, publish_image


def docker_image_tag(args):
    add_image_tag(args.image, args.tag, args.registry)


def docker_image_publish(args):
    publish_image(args.image, args.registry)


parser = argparse.ArgumentParser(prog="docker-publish", description="")
subparser = parser.add_subparsers(help="sub-command help")

tag = subparser.add_parser("tag")
tag.add_argument("image", type=str, help="Image name.")
tag.add_argument("tag", type=str, help="Tag to append to image.")
tag.add_argument("--registry", required=False, type=str,
                 help="URL of registry.")
tag.set_defaults(func=docker_image_tag)

publish = subparser.add_parser("publish")
publish.add_argument("image", type=str, help="Image name.")
publish.add_argument("--registry", required=False, type=str,
                     help="URL of registry to publish to.")
publish.set_defaults(func=docker_image_publish)

args = parser.parse_args()
if hasattr(args, 'func'):
    args.func(args)
